### ISSUE TITLE
Pool Fee 

### ISSUE THREAD

**Issue by mmitech** [ming08108/EtherPool#1]
I can't figure where to set the Pool fee ? it would be great if we move that to the config file.

**Comment by ming08108** [comment]
There is currently no way to set the pool fee in this version. If you need to implement a fee I suggest modifying the payment script. It should be relatively simple. Let me know if you need help.

**Comment by mmitech** [comment]
Wouldn't be better if it was in the update balance script like something like balance = (reward - (reward \* fee));  and make the fee a variable that can be set in the config file ? 

This way the stats would be accurate and you won't get the " I got less than what it shows" classic problem.

**Comment by ming08108** [comment]
That would work too. You would need to save the fees somewhere or else the updatebalances will not remember between runs.

**Comment by mmitech** [comment]
the fee should be called from the config file.

**Comment by ming08108** [comment]
Please submit a pull request and I will merge.

**Comment by mmitech** [comment]
I will when I get it to work.
