### ISSUE TITLE
installation of ethashjs fails

### ISSUE THREAD

**Issue by bernardpeh** [ming08108/EtherPool#3]
looks like 

"ethashjs": "0.0.3"

no longer works.

**Comment by ming08108** [comment]
Looks like you can change it to the latest version. Though the problem might lie somewhere else. I find that some versions of NPM have trouble installing ethashjs. Let me know if that fixes the issue.

**Comment by bernardpeh** [comment]
thanks for replying. yes, I couldn't install ethashjs 0.0.3. what node and npm version do u use?

my node version v0.10.43
npm: 3.8.3

When updated to ethashjs 0.04 or 0.0.7, installation works fine but i could no longer submit shares. run.js hanged once a solution is found and submitted. I figured the problem lies in about line 40 of shareHandler.js

ethash.loadEpoc(block, function(){
  var a = ethash.run(new Buffer(headerHash, 'hex'), new Buffer(nonce, 'hex'))
  ,,,

not sure what happens there, maybe ethashjs wasn't install properly. I haven't dig in yet.

**Comment by ming08108** [comment]
Oh its fine. The first time a share is submitted (or a new epoch) ethash has to generate a new cache to validate shares. It should not take much more than a couple minutes.

**Comment by bernardpeh** [comment]
He problem is run.js hanged and then died a few secs later

**Comment by ming08108** [comment]
Did it give any error messages before it died?

**Comment by bernardpeh** [comment]
apologies, should have pasted the error sooner. when run.js died after a solution is found, it gave

/home/me/kbpool/node_modules/ethashjs/index.js:54
  var mix = Buffer.concat(Array(mixhashes).fill(s))
                                           ^
TypeError: Object , has no method 'fill'
    at Ethash.run (/home/me/kbpool/node_modules/ethashjs/index.js:54:44)
    at /home/me/kbpool/shareHandler.js:41:19
    at Object._onImmediate (/home/me/kbpool/node_modules/levelup/lib/levelup.js:258:9)
    at processImmediate [as _immediateCallback](timers.js:363:15)

node: v0.10.43
npm: v3.8.3

package.json:
{
  "name": "ethpool",
  "version": "1.0.0",
  "description": "",
  "main": "run.js",
  "dependencies": {
    "body-parser": "^1.13.3",
    "express": "^4.13.3",
    "ethashjs": "0.0.7",
    "ethereumjs-util": "~1.3.6",
    "bn.js": "~3.1.1",
    "redis": "~2.0.0",
    "bloom-filter": "~0.2.0",
    "levelup": "~1.2.1",
    "memdown": "~1.0.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

**Comment by ming08108** [comment]
This seems to be a javascript issue caused by ethash trying to use some ES6 features. Can you try installing a newer version of node? Ubuntu uses a old version of nodejs in the default package manager. 

https://nodejs.org/en/download/package-manager/

**Comment by bernardpeh** [comment]
tks for that. looks like ubuntu comes with 0.10 by default. I installed node v4 and it works.
